### ISSUE TITLE
RNCNetInfo.getCurrentConnectivity is not a function

### ISSUE THREAD

**Issue by earthlingstd** [GetStream/stream-chat-react-native#45]
**How to reproduce**
```
  const ThreadScreen = (props: IProps) => {
  const [thread, setThread] = useState(null)
  const [channel, setChannel] = useState(null)

  useEffect(() => {
    getChannel('tempID').then(c => {
      setChannel(c)
      getThread('3d3ba947-f589-4e70-9bcf-06510e6e5498').then(t => {
        setThread(t)
      })
    })
  })

  return (
    <SafeAreaView>
      <Chat client={StreamIOClient}>
        <Channel client={StreamIOClient} channel={channel} thread={thread} dummyProp="DUMMY PROP">
          <View
            style={{
              display: 'flex',
              height: '100%',
              justifyContent: 'flex-start',
            }}
          >
            <Thread thread={thread} />
          </View>
        </Channel>
      </Chat>
    </SafeAreaView>
  )
}
```
**Environment**
RN: 0.60.4
@react-native-community/netinfo: 4.1.4
**Screenshot**
![img](https://i.imgur.com/02cwd8G.png)

**Comment by hongsa** [comment]
I think netinfo only 2 version is available..
Why??

**Comment by vishalnarkhede** [comment]
Hey @earthlingstd 

We don't support RN 0.60 yet (due to linking behavior). I think the issue is coming from linking issue of NetInfo library. 

Can you try the same app on RN 0.59 please and let us know if it works for you?

**Comment by hongsa** [comment]
I use rn 0.59
and only support netinfo 2.0.7 right?

**Comment by vishalnarkhede** [comment]
Hey @hongsa ,

Yes currently we have support for 2.0.7, for compatibility reasons with RN 0.57 and 58.

We haven't upgraded it yet. What version are you looking to use?

**Comment by emielvanliere** [comment]
FWIW, I can use `stream-chat-react-native` on RN 0.60.4 just fine. The only thing I need to do is to manually upgrade NetInfo to 4.1.4. What is the timeframe for support RN 0.60?

In the meantime, I could build stream-chat-react-native myself. Are there any instructions for doing that?

thanks

**Comment by earthlingstd** [comment]
> Hey @earthlingstd
> 
> We don't support RN 0.60 yet (due to linking behavior). I think the issue is coming from linking issue of NetInfo library.
> 
> Can you try the same app on RN 0.59 please and let us know if it works for you?

The lib works fine with RN 0.60. I dont have any problem with auto linking. The only issue is with NetInfo library. It'd be very great if you increase NetInfo version in your dependency package to the latest version

**Comment by vishalnarkhede** [comment]
Hey @emielvanliere @earthlingstd 

Now I am working on fixing these issues with external dependencies for upgrade to RN 0.60. We shall publish it in next couple of days. I will keep you updated here!!

**Comment by EJohnF** [comment]
We are considering you lib as an alternative to move out from sendbird, and from the very beginning meet this problem. Not cool :-(

**Comment by EJohnF** [comment]
with 0.59 I was able to run the tutorial code successfully. 
with 0.60, even though I overcome this NetInfo problem, there are constantly other errors happens somewhere inside, like `this.messages.flatMap is not a function` and some similar. resulting that I couldn't send messages to channel or thread. 

Big hopes on the new update

**Comment by vishalnarkhede** [comment]
@EJohnF Can you tell me what android version and emulator are you using for testing?

**Comment by vishalnarkhede** [comment]
Hey @emielvanliere @earthlingstd @EJohnF @hongsa 

I have published v0.2.0 for our react native sdk, which comes with support for React Native 0.60. It should get rid of issues with netinfo package altogether.
I had to take out external dependencies like netinfo, image picker and document picker from hard dependencies to peerDependencies. Please give it a try and let me know your feedback or issues (if any).

How to use for rn 0.60 app: https://github.com/GetStream/stream-chat-react-native#for-react-native--060-1

Upgrading from our sdk 0.1.x to 0.2.x: https://github.com/GetStream/stream-chat-react-native#upgrade

**Comment by EJohnF** [comment]
Sorry about my last comment, I figured out that the problem was in the integration of your Chat framework with react-native-navigation (found another issue here, which gave me a hint that object is not correctly transferred via props) 

I'll definitely give a shot for a new version today (even though we already made it works with the old one)

**Comment by vishalnarkhede** [comment]
Hey @EJohnF , 

Yeah, passing a channel via prop in `react-native-navigation` won't work. It messes up with the prop completely. @hongsa had the similar issue as well - https://github.com/GetStream/stream-chat-react-native/issues/48#issuecomment-522055164

**Comment by EJohnF** [comment]
about integration with 0.60RN and 0.2.x of chat
After the update works fine for me. just two notices: 
1) it worked before also since I added NetInfo manually. But good that not we can use a newer version
2)  not sure, need to warn people who use react-native-navigation or not. That autolink for android is not working there yet, so need to link dependencies of Chat library manually.

**Comment by vishalnarkhede** [comment]
@EJohnF 
Thanks for the feedback. We will add the concerns regarding `react-native-navigation` to documentation :)
