### ISSUE TITLE
[v1.1.0] this.attachActionSheet.show is not a function

### ISSUE THREAD

**Issue by giautm** [GetStream/stream-chat-react-native#270]
I ran into this issue after upgrade to v1.1.0

![image](https://user-images.githubusercontent.com/12751435/89095755-1c1aec80-d3fb-11ea-845a-acd595fa6a7c.png)

https://github.com/GetStream/stream-chat-react-native/blob/10f94551dc9cd09865728ea2f27e466329baac08/src/components/MessageInput/MessageInput.js#L906

https://github.com/GetStream/stream-chat-react-native/blob/10f94551dc9cd09865728ea2f27e466329baac08/src/components/MessageInput/MessageInput.js#L823

Why setRef of Input into ActionSheet?
https://github.com/GetStream/stream-chat-react-native/blob/10f94551dc9cd09865728ea2f27e466329baac08/src/components/MessageInput/MessageInput.js#L884-L903

Also ActionSheet, and AutoCompleteInput used the same referencet
https://github.com/GetStream/stream-chat-react-native/blob/10f94551dc9cd09865728ea2f27e466329baac08/src/components/MessageInput/MessageInput.js#L875-L877

https://github.com/GetStream/stream-chat-react-native/blob/10f94551dc9cd09865728ea2f27e466329baac08/src/components/MessageInput/MessageInput.js#L934-L942

Your chat kit have very low quality, I ran into 2 issue after upgrade. Please preview code carefully.

gz#5102

**Comment by giautm** [comment]
I also working on refactor MessageInput to using hooks, and fix this bug. Will send PR before next Monday.
